package com.oop.game.JAR.enums;

public enum MessageType {

    REGIS_REQUEST,
    LOGIN_REQUEST,
    LOGOUT_REQUEST,
    PLAYER_CREATE_REQUEST,
    PLAYER_LIST_REQUEST,
    INVITE_REQUEST,
    LEADERBOARD_REQUEST,

    REGIS_RESPONSE,
    LOGIN_RESPONSE,
    USER_RESPONSE,
    PLAYER_CREATE_RESPONSE,
    PLAYER_LIST_RESPONSE,
    PLAYER_STATUS_UPDATE,
    INVITE_RESPONSE,
    LEADERBOARD_RESPONSE,

    // Game play
    MATCH_START,
    MOVE_REQUEST,
    MOVE_RESULT,
    COLOR_SWAP_REQUEST,
    MATCH_STATE_UPDATE,
    MATCH_END,
    PLAYER_LEFT,

    // Power-ups
    POWERUP_USE,
    POWERUP_EFFECT,

    ERROR

}
